### ISSUE TITLE
chapter 4: change image size

### ISSUE THREAD

**Issue by m4ln** [PacktPublishing/Hands-On-Generative-Adversarial-Networks-with-PyTorch-1.x#3]
Thank you for providing the book and the code examples.
I am using the code from chapter 4 to generate new images from histopathological data.
The output size from the code is 64x64, but I would like to generate bigger images, i.e 256x256 or 512x512.
I adapted the generators and discriminators layer by incresing the input and output sizes, but I still have a bug. 
My guess is that I have to change the kernel sizes, stride and/or padding. 
Do you have any suggestion?
Thanks a lot!

**Comment by m4ln** [comment]
ok I found a simple solution, you basically just need to add more trans-conv and conv layers to the generator and discriminator respectively.

**Comment by MattTucker22689** [comment]
I'm curious, what was your solution? I'm trying to work with 1024x1024 and modified the code. But now I'm getting a memory error that I'm trying to work out:

```
Traceback (most recent call last):
  File "/home/DCGAN_/dcgan.py", line 178, in <module>
    netD = Discriminator().to(device)
  File "/home/w223u672/virtualenvs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/home/w223u672/virtualenvs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/w223u672/virtualenvs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/w223u672/virtualenvs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/home/w223u672/virtualenvs/test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.00 GiB (GPU 0; 15.77 GiB total capacity; 13.43 GiB already allocated; 1.55 GiB free; 13.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Here's how I modified the code.

```
class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(Z_DIM, G_HIDDEN * 256, 4, 1, 0, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 256),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 256, G_HIDDEN * 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 128),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 128, G_HIDDEN * 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 64),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 64, G_HIDDEN * 32, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 32),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 32, G_HIDDEN * 16, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 16),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 16, G_HIDDEN * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 8),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 8, G_HIDDEN * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 4),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 4, G_HIDDEN * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN * 2),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN * 2, G_HIDDEN, 4, 2, 1, bias=False),
            nn.BatchNorm2d(G_HIDDEN),
            nn.ReLU(True),

            nn.ConvTranspose2d(G_HIDDEN, IMAGE_CHANNEL, 4, 2, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, input):
        return self.main(input)


class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(IMAGE_CHANNEL, D_HIDDEN, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN, D_HIDDEN * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 2),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 2, D_HIDDEN * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 4),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 4, D_HIDDEN * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 8),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 8, D_HIDDEN * 16, 4, 1, 0, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 16),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 16, D_HIDDEN * 32, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 32),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 32, D_HIDDEN * 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 64),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 64, D_HIDDEN * 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 128),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 128, D_HIDDEN * 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(D_HIDDEN * 256),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(D_HIDDEN * 256, 1, 4, 1, 0, bias=False),
            nn.Sigmoid()
        )

    def forward(self, input):
        return self.main(input).view(-1, 1).squeeze(1)
```

**Comment by m4ln** [comment]
If you have memory issues, I would suggest checking your batch size. It's possible that your batch size is too big, so try using a smaller one. If you haven't tried it already, you could also test your code with smaller image sizes first and then gradually increase the image and batch sizes.
In my solution, I also added extra layers similar to your solution, but in the end, I removed them and used a smaller image size because I obtained better results (I don't clearly remember the exact reasons but it was fine for me like that so I didn't investigate further)
Don't know if it helps but you can find my code here (I commented out the extra layers) http://gitlab.medma.uni-heidelberg.de/digital-pathology/pytorch_dcgan/blob/master/dcgan.py
Good luck and please tell if you find a solution!
